### ISSUE TITLE
JaCoCo plugin execution failed when building Jeka

### ISSUE THREAD

**Issue by amottier** [jeka-dev/jeka#239]
I'm trying to build Jeka and run SonarQube analysis by running: `ant -Dsonar.host.url=${SONAR_URL} -Dsonar.login=${SONAR_LOGIN} -f .github/workflows/build.xml -Dbasedir=`.` run` on Jeka tag `0.10.35` and it failed with the following stack trace:
```
     [java] java.lang.NullPointerException: Cannot invoke "java.net.URL.getPath()" because "<parameter1>" is null
     [java]     at dev.jeka.core.api.utils.JkUtilsIO.copyUrlContentToCacheFile(Unknown Source)
     [java]     at dev.jeka.plugins.jacoco.JkJacoco$EmbeddedToolProvider.<init>(Unknown Source)
     [java]     at dev.jeka.plugins.jacoco.JkJacoco.ofEmbedded(Unknown Source)
     [java]     at MasterBuild.<init>(MasterBuild.java:73)
     [java]     at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
     [java]     at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
     [java]     at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
     [java]     at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
     [java]     at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
     [java]     at dev.jeka.core.api.utils.JkUtilsReflect.newInstance(Unknown Source)
     [java]     at dev.jeka.core.tool.JkRuntime.instantiate(Unknown Source)
     [java]     at dev.jeka.core.tool.JkRuntime.getBean(Unknown Source)
     [java]     at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
     [java]     at java.base/java.util.stream.DistinctOps$1$2.accept(DistinctOps.java:174)
     [java]     at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
     [java]     at java.base/java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1242)
     [java]     at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
     [java]     at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
     [java]     at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
     [java]     at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
     [java]     at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
     [java]     at dev.jeka.core.tool.JkRuntime.init(Unknown Source)
     [java]     at dev.jeka.core.tool.Engine.execute(Unknown Source)
     [java]     at dev.jeka.core.tool.Main.main(Unknown Source)
     [java]     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
     [java]     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
     [java]     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
     [java]     at java.base/java.lang.reflect.Method.invoke(Method.java:568)
     [java]     at dev.jeka.core.api.utils.JkUtilsReflect.invoke(Unknown Source)
     [java]     at dev.jeka.core.api.utils.JkUtilsReflect.invokeMethod(Unknown Source)
     [java]     at dev.jeka.core.api.utils.JkUtilsReflect.invokeStaticMethod(Unknown Source)
     [java]     at dev.jeka.core.api.java.JkClassLoader.invokeStaticMethod(Unknown Source)
     [java]     at dev.jeka.core.tool.Main.main(Unknown Source)
```

Build of version `0.10.31` is successful.

So it seems caused by changes introduces in version `0.10.32`. More specifically by https://github.com/jeka-dev/jeka/commit/6a51dc63028a70aa0fa9eca1645422c6a75bf532#diff-dba7b2cfc87210e584c65671a6db2b43a8377f56632f126bf1171b9cffc5b329R326

Logs of the build are visible at https://gitlab.ow2.org/ow2/oscar/jeka/-/jobs/130999 and the CI job definition at https://gitlab.ow2.org/ow2/oscar/jeka/-/blob/main/.gitlab-ci.yml#L68

**Comment by djeang** [comment]
HI,

The last snapshot fixes this issue.

Regards

**Comment by amottier** [comment]
Thanks, that was fast!

I can confirm that the issue is fixed :+1:
